services:
  - type: web
    name: karim-portfolio
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
